version: "3"

tasks:
  build:
    cmd: docker build -t franciscoklogan/openfga-mcp:latest .

  push:
    deps: [build]
    cmds:
      - mkdir -p /tmp/docker
      - echo "$DOCKER_HUB_PASSWORD" | docker login -u franciscoklogan --password-stdin
      - docker --config /tmp/docker push franciscoklogan/openfga-mcp:latest
      - rm -rf /tmp/docker

